group = core
admin-port = 13000
smsbox-port = 13001
admin-password = admin
status-password = admin
log-file = /tmp/kannel.log
log-level = 1
box-allow-ip = 127.0.0.1;MMSC_IP

group = smsbox
bearerbox-host = 127.0.0.1
sendsms-port = 13013
global-sender = 4040000001

group = sendsms-user
username = mmsc
password = mmsc123

group = smsc
smsc = smpp
smsc-id = smsc
host = OSMOMSC_IP
port = 2775
smsc-username = mmsc
smsc-password = mmsc123
transceiver-mode = true
system-type = ""
log-level = 2
