group = core
log-file = /tmp/mbuni.log
log-level = 1

group = mbuni
hostname = 172.22.1.160
storage-directory = /tmp/mms-storage
sendmms-port = 8181
mms-port = 8090
sendsms-url = http://127.0.0.1:13013/cgi-bin/sendsms
sendsms-username = mmsc
sendsms-password = mmsc123
sendsms-global-sender = 4040000001
local-prefixes = 0;1;2;3;4;5;6;7;8;9
default-message-expiry = 259200
max-message-expiry = 604800
mms-client-msisdn-header = X-MSISDN
strip-prefixes = +91;+
content-adaptation = false

group = mmsproxy
name = local-delivery
host = 172.22.1.160

group = mmsc
id = local
type = mm7
incoming-port = 8190
allow-ip = 0.0.0.0/0
no-sender-address = true

group = send-mms-user
username = mmsc
password = mmsc123
faked-sender = 4040000001
