group = core
log-file = /tmp/mbuni.log
log-level = 1

group = mbuni
hostname = MMSC_IP
storage-directory = /tmp/mms-storage
sendmms-port = 8181
mms-port = 8090
mm7-port = 8190
sendsms-url = http://127.0.0.1:13013/cgi-bin/sendsms
sendsms-username = mmsc
sendsms-password = mmsc123
sendsms-global-sender = 4040000001
local-prefixes = 0;1;2;3;4;5;6;7;8;9
default-message-expiry = 259200
max-message-expiry = 604800
mms-client-msisdn-header = X-MSISDN
strip-prefixes = +91;+
content-adaptation = false
resolver-library = builtin:shell
resolver-module-parameters = /etc/mmsc/resolve_mmsc.sh
email2mms-relay-hosts = MMSC_IP
queue-run-interval = 5
mm1-queue-run-interval = 5
send-attempt-back-off = 10
mmsbox-admin-port = 8183
admin-password = mmsc123

group = mmsproxy
name = local-delivery
host = MMSC_IP

group = mmsc
id = local
type = soap
vasp-id = mmsc
mmsc-url = http://mmsc:mmsc123@127.0.0.1:8190/mm7
incoming-port = 8182
incoming-username = mmsc
incoming-password = mmsc123
allow-ip = 127.0.0.1;MMSC_IP
allowed-prefix = 0;1;2;3;4;5;6;7;8;9;+
no-sender-address = true

group = mms-vasp
vasp-id = mmsc
type = soap
short-codes = 4040000001;9876540700;9876541000;9876542000
vasp-username = mmsc
vasp-password = mmsc123
vasp-url = http://127.0.0.1:8182/mm7

group = send-mms-user
username = mmsc
password = mmsc123
faked-sender = 4040000001

